stages:
  - comment
  - release

before_script:
  - pnpm i --frozen-lockfile

comment:
  image: node:lts-alpine
  stage: comment
  only:
    - merge_requests
  script: pnpm run changesets-gitlab comment

release:
  image: node:lts-alpine
  only:
    - main
  script: pnpm run changesets-gitlab
  variables:
    INPUT_PUBLISH: pnpm run release
