comment:
  image: node:24
  needs: []
  only:
    - merge_requests
  script: npx -y changesets-gitlab comment


main:
  id_tokens:
    NPM_ID_TOKEN:
      aud: "npm:registry.npmjs.org"
  image: node:24
  needs: []
  script:
    - corepack enable
    - pnpm i --frozen-lockfile
    - pnpm run build
    - pnpm run lint
    - pnpm run test
    - bash -x ./scripts/changesets.sh
    - pnpm run deploy
  variables:
    INPUT_PUBLISH: pnpm run changeset publish
    INPUT_REMOVE_SOURCE_BRANCH: "true"
