comment:
  image: node:22
  needs: []
  only:
    - merge_requests
  script: npx -y changesets-gitlab comment

main:
  image: node:22
  needs: []
  script:
    - npm install -g pnpm
    - pnpm i --frozen-lockfile
    - pnpm run build
    - pnpm run lint
    - pnpm run test
    - npx changesets-gitlab
    - pnpm run deploy
  variables:
    INPUT_PUBLISH: sh ./scripts/changesets-publish.sh
    INPUT_VERSION: sh ./scripts/changesets-version.sh
    INPUT_REMOVE_SOURCE_BRANCH: "true"
